language: python
python:
  - "2.7"

env: PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache

cache:
  directories:
  - $HOME/.pip_download_cache

install:
  - pip install pep8 nose
  - pip install -r ./requirements.txt

before_script:
  - "pep8 ./"
script:
  - nosetests
